In [6]:
# from google.colab import drive
# drive.mount('/content/gdrive')

**Read me:**
In this notebook we make a grid of the laser parameters to feed to the NN model and predict the channel dimensions. What we do
- reading experimental data
- finding the list of used parameters as the grid parametrs should be the same range as experimental data
- set nested for-loops for making combinations and save it


In [1]:
"""import packages you need"""
import numpy as np
import pandas as pd
import seaborn as sns
# import matplotlib.pyplot as plt 

# from sklearn.preprocessing import MinMaxScaler, PolynomialFeatures
# from sklearn.metrics import accuracy_score, mean_squared_error
# from sklearn.model_selection import KFold
# from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
# from sklearn.linear_model import LinearRegression, Ridge, Lasso
# from sklearn.pipeline import Pipeline
# from sklearn.utils import shuffle

# from xgboost import XGBRegressor
# import torch
# import torch.nn as nn
# from torch.utils.data import Dataset
# torch.manual_seed(20210614)
# device = torch.device("cuda")

In [8]:
# df1 = pd.read_excel('RawData/Machine Learning Data_01.xlsx')

# df1.dropna(how='any', axis=1, inplace = True) 

# print(f'shape of the data frame: {df1.shape}')

In [2]:
"""After tunning data"""

df_0 = pd.read_csv('RawData/two_widths/Param0_2width.csv')
df_1 = pd.read_csv('RawData/two_widths/Param1_2width.csv')
df_2 = pd.read_csv('RawData/two_widths/Param2_2width.csv')
df_3 = pd.read_csv('RawData/two_widths/Param3_2width.csv')
df_4 = pd.read_csv('RawData/two_widths/Param4_2width.csv')

df1 = pd.concat([df_0, df_1, df_2, df_3, df_4], axis = 0, ignore_index = True)

In [10]:
# combined_Exp = pd.read_csv('RawData/AllExpComb_tuned.csv')
# df1 = shuffle(combined_Exp, random_state=20210614)

In [11]:
# df_new = pd.read_excel('RawData/New set of data.xlsx', header=1)

# df_new.drop(df_new.index[df_new['Angle (deg)'] == 0], inplace = True)
# df_new.drop(df_new.index[df_new['Depth (um)'] == 0], inplace = True)

# DATA_new = np.c_[df_new.iloc[:,3].values, df_new.iloc[:,2].values, df_new.iloc[:,4].values,\
#                 df_new.iloc[:,5].values, df_new.iloc[:,1].values, df_new.iloc[:,6].values,\
#               df_new.iloc[:,7].values ] 

# column_names = ['Frequency', 'Speed', 'Amplitude', 'Passes','Focal_Position',
#                           'Depth','Angle']

# df1 = pd.DataFrame(DATA_new, columns = column_names)

### Exploring the data set

In [12]:
# df1.columns = df1.columns.str.replace(' ', '')
df1.keys()

Index(['Frequency', 'Speed', 'Amplitude', 'Passes', 'Focal_Position', 'Depth',
       'Top_width', 'Bot_width'],
      dtype='object')

In [3]:
"""Listing the values of each parameter"""

print('Exp Params. after tuning:\n')
freq = df1.Frequency.drop_duplicates().values.round(3)
# print(freq.shape, '\n min :', min(freq),'\n max:' , max(freq))
freq.sort()
print('Used frequencies are :\n', freq)

speed = df1.Speed.drop_duplicates().values.round(3)
# print(speed.shape,'\n min:', min(speed),'\n max:', max(speed))
speed.sort()
print('\nUsed speeds are :\n', speed)

Ampl = df1.Amplitude.drop_duplicates().values.round(3)
# print(Ampl.shape,'\n min:', min(Ampl),'\n max:', max(Ampl))
Ampl.sort()
print('\nUsed Amplitudes are :\n', Ampl)

no_pass = df1.Passes.drop_duplicates().values.round(3)
# print(no_pass.shape,'\n min:', min(no_pass),'\n max:', max(no_pass))
no_pass.sort()
print('\nUsed no. of passes are :\n', no_pass)

pos = df1.Focal_Position.drop_duplicates().values.round(3)
# print(pos.shape,'\n min:', min(pos),'\n max:', max(pos))
pos.sort()
print('\nUsed focal positions are :\n', pos)



Exp Params. after tuning:

Used frequencies are :
 [ 200.  300.  480.  600.  800. 1000. 1200. 1400. 1600.]

Used speeds are :
 [ 5.   7.5 12.  15.  20.  25.  30.  35.  40. ]

Used Amplitudes are :
 [0.1 0.2 0.3 0.4 0.5 0.7 0.8 0.9 1.  1.2]

Used no. of passes are :
 [ 10.  15.  20.  30.  40.  80. 120. 160.]

Used focal positions are :
 [91.676 92.057 92.438 92.819 93.2  ]


In [14]:
""" Counting the number of occurances of each instant"""

# from collections import Counter

# frequency = df1.Frequency.values.round(3)
# linear_speed = df1.Speed.values.round(3)
# Ampllitude = df1.Amplitude.values.round(3)
# number_pass = df1.Passes.values.round(3)
# focal_position = df1.Focal_Position.values.round(3)

# print('Exp1 frequencies:')
# print(Counter(frequency))

# print('\n Exp1 Speeds:')
# print(Counter(linear_speed))

# print('\n Exp1 Amplitudes:')
# print(Counter(Ampllitude))

# print('\n Exp1 No. of Passes:')
# print(Counter(number_pass))

# print('\n Exp1 focal Position:')
# print(Counter(focal_position))

' Counting the number of occurances of each instant'

In [15]:
"""Measured depth and widths"""
Depth = df1.Depth.drop_duplicates().values.round(2)
print('\n',Depth.shape,'\n min Depth:', min(Depth),'\n max Depth:', max(Depth))
Depth.sort()
print('\nMeasured Depth are :\n', Depth)

Top_w = df1.Top_width.drop_duplicates().values.round(2)
print('\n',Top_w.shape,'\n min top_width:', min(Top_w),'\n max top_width:', max(Top_w))
Top_w.sort()
print('\nMeasured Top_width are :\n', Top_w)


Bot_w = df1.Bot_width.drop_duplicates().values.round(2)
print('\n',Bot_w.shape,'\n min bottom_width:', min(Bot_w),'\n max bottom_width:', max(Bot_w))
Bot_w.sort()
print('\nMeasured Bot_width are :\n', Bot_w)


 (123,) 
 min Depth: 3.45 
 max Depth: 1197.31

Measured Depth are :
 [   3.45    4.93    6.45   35.05   39.91   67.55   70.64   73.93   78.46
   87.21   89.76   91.21   92.65  115.35  116.28  117.76  122.93  125.88
  126.03  131.8   133.92  143.43  153.52  153.87  161.68  164.42  171.66
  171.7   173.95  174.92  177.03  177.29  182.18  183.31  184.33  188.51
  201.42  206.52  209.07  210.9   212.55  214.92  221.04  224.43  226.86
  226.92  231.9   238.31  245.26  245.67  247.33  247.34  250.41  251.98
  258.59  265.8   272.44  295.04  296.42  303.03  304.18  304.66  306.55
  308.27  323.5   325.22  330.92  336.52  338.83  346.19  348.1   360.5
  367.66  370.66  372.63  378.05  388.15  395.62  401.07  404.71  408.05
  423.24  425.73  455.52  461.3   461.36  483.79  485.07  498.65  507.55
  515.12  517.73  563.77  569.69  572.83  573.91  594.35  631.13  637.41
  657.24  662.28  681.88  710.99  732.06  825.25  859.6   865.62  887.63
  936.02  975.17  985.38  993.86 1006.46 1029.73 1038.

In [16]:
df1.Frequency.values/df1.Speed.values

array([40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40.,
       40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40.,
       40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40.,
       40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40.,
       40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40.,
       40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40.,
       40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40.,
       40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40.,
       40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40.,
       40., 40., 40., 40., 40., 40., 40.])

# Making data frames to feed to the trained model 

- Using only used laser parameters
- Using finer mesh of laser parameters

In [17]:
"""Making a dataframe with all the reported values for parametres
In case we want some restrictions on the combination of parameters we can
give it initial values like: ``pos = [93.2]`` or as if statements like: 
if (s*1000/f) <= 35
Just double check the indentations when you include if statements
"""


# pos = [93.2]
DATA = []
for f in freq:
#     for s in speed:
    for a in Ampl:
        for np in no_pass:
            for p in pos:
#                     if (f/s) == 40:
                data_point = [f, f/40, a, np, p] 
                DATA.append(data_point)

    

import numpy as np
Data = np.array([np.array(xi) for xi in DATA])

print(f"Shape of the new data frame: {Data.shape}")

df_target = pd.DataFrame(Data, columns = 
    ['Frequency', 'Speed', 'Amplitude', 'Passes', 'Focal_Position'])
                    

# df_target.to_csv(r'/content/gdrive/MyDrive/PostDoc/MLFE/Python_codes/RawData/UsedVal_comb.csv', header=True, index = False)

df_target.shape

Shape of the new data frame: (3600, 5)


(3600, 5)

In [18]:
# df_target.head()
df_target.Frequency/df_target.Speed

0       40.0
1       40.0
2       40.0
3       40.0
4       40.0
        ... 
3595    40.0
3596    40.0
3597    40.0
3598    40.0
3599    40.0
Length: 3600, dtype: float64

In [19]:
"""Making a dataframe with finer mesh of possible values for parametres"""


DATA = []
for f in np.arange(freq.min(), freq.max()+50, 50):
#     for s in np.arange(speed.min(), speed.max()+1, 1) :
    for a in np.arange(Ampl.min(), Ampl.max()+0.1, 0.1):
        for no_p in np.arange(no_pass.min(), no_pass.max()+5, 5):
            for p in pos:
                data_point = [f, f/40, a, no_p, p] 
                DATA.append(data_point)

    

import numpy as np
Data = np.array([np.array(xi) for xi in DATA])

print(f"Shape of the new data frame: {Data.shape}")

df_possible = pd.DataFrame(Data, columns = 
    ['Frequency', 'Speed', 'Amplitude', 'Passes', 'Focal_Position'])
                    
df_possible.to_csv(r'RawData/two_widths/Grid_TunedLaserParam.csv', header=True, index = False)
df_possible.head()

Shape of the new data frame: (53940, 5)


Frequency  Speed  Amplitude  Passes  Focal_Position
0      200.0    5.0        0.1    10.0          91.676
1      200.0    5.0        0.1    10.0          92.057
2      200.0    5.0        0.1    10.0          92.438
3      200.0    5.0        0.1    10.0          92.819
4      200.0    5.0        0.1    10.0          93.200

In [10]:
# target = pd.read_csv("Data/Used_combination.csv")
# org = pd.read_excel('Data/Machine Learning Data_org.xlsx')

# org.dropna(how='any', axis=1, inplace = True) 
# fig, axs = plt.subplots(nrows = 1, ncols=2, figsize = (12,4))


# sns.distplot(df_target.Frequency, ax=axs[0], color = 'b', label = 'Exp Freq')
# sns.distplot(df_possible.Frequency, ax=axs[0], color = 'r', label = 'Possible Free')

# sns.distplot(df_target.Amplitude, ax=axs[1], color = 'b', label = 'Exp Amp')
# sns.distplot(df_possible.Amplitude, ax=axs[1], color = 'r', label = 'Possible Amp')

# axs[0].legend(fontsize=12)
# axs[1].legend(fontsize=12)
# axs[0].set_xlabel('Freq', fontsize=20)
# axs[1].set_xlabel('Amp', fontsize=20)